FROM node:20
EXPOSE 8080
WORKDIR /opt/server
COPY package.json .
COPY server.js .
RUN npm install
ENV REDIS_HOST=redis \
    CATALOGUE_HOST=catalouge \
    CATALOGUE_PORT=8080
CMD [ "node","server.js" ]