FROM node:20.19.5-alpine3.21 AS build
WORKDIR /opt/server
COPY package.json *.js ./
RUN npm install


FROM node:20.19.5-alpine3.21
EXPOSE 8080
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop && \
    chown -R roboshop:roboshop /opt/server
LABEL com.project="roboshop" \
      component="cart" \
      cretaedBy="Rohith"
COPY --from=build --chown=roboshop=roboshop /opt/server   /opt/server
ENV REDIS_HOST="redis" \
    CATALOGUE_HOST="catalogue" \
    CATALOGUE_PORT="8080"
USER roboshop
CMD [ "server.js" ]
ENTRYPOINT [ "node" ]


# FROM node:20
# EXPOSE 8080
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV REDIS_HOST="redis" \
#     CATALOGUE_HOST="catalogue" \
#     CATALOGUE_PORT="8080"
# CMD [ "node","server.js" ]