FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY static /usr/share/nginx/html/static

RUN chmod -R 755 /usr/share/nginx/html
