FROM python:3.9.25-alpine3.21 as builder
WORKDIR /opt/server
COPY requirements.txt .
# install build dependenices
RUN apk add --no-cache \
    build-base \
    linux-headers \
    pcre-dev
# Install Python requirements
COPY requirements.txt .
RUN pip3 --prefix=/install -r requirements.txt

FROM python:3.9.25-alpine3.21
EXPOSE 8080
WORKDIR /opt/server
# install runtime dependencies
RUN apk add --no-cache pcre
# create non root user
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
LABEL com.project="roboshop" \
      component="payment" \
      createdBy="rohith"
ENV CART_HOST="cart" \
    CART_PORT="8080" \
    USER_HOST="user" \
    USER_PORT="8080" \
    AMQP_HOST="rabbitmq" \
    AMQP_USER="roboshop" \
    AMQP_PASS="roboshop123"
# copy installed packages
COPY --from=builder /install /usr/local
# copy app files
COPY --chown=roboshop:roboshop payment.ini *.py requirements.txt ./
USER roboshop
CMD [ "uwsgi" , "--ini" , "payment.ini" ]


# FROM python:3.9
# EXPOSE 8080
# WORKDIR /opt/server
# COPY *.py .
# COPY payment.ini .
# COPY requirements.txt .
# RUN pip3 install -r requirements.txt
# ENV CART_HOST="cart" \
#     CART_PORT="8080" \
#     USER_HOST="user" \
#     USER_PORT="8080" \
#     AMQP_HOST="rabbitmq" \
#     AMQP_USER="roboshop" \
#     AMQP_PASS="roboshop123"
# CMD [ "uwsgi", "--ini","payment.ini" ]
