FROM node:20
WORKDIR /opt/server
COPY package.json .
COPY server.json .
RUN npm install
ENV REDIS_URL="redis://redis:6379" \
    MONGO_URL="mongodb://mongodb:27017/users"
EXPOSE 8080
CMD [ "node","server.js" ]
